### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cjhong6**

### CODE REVIEW

**Comment by paulpowang** [comment]
no need

**Comment by codepathreview** [comment]
👍 Nice work on the second implementation sprint! There's one week left to complete all of the required stories. Excited to see your progress next week!  
/cc @codepathreview

**Comment by codepathreview** [comment]
👍 Great job getting all the required stories done! This is a big milestone as now it's all about adding optionals and additional polish to the app. 
/cc @codepathreview

**Comment by codepathreview** [comment]
👍 Thanks for submitting your progress for this sprint! Next week we go into the final sprint before demo day. Make sure you leave enough time to put together and practice your demo. 
/cc @codepathreview

**Comment by codepathreview** [comment]
👍 Thanks for submitting your final GIF walkthrough! It's pretty remarkable when you step back and think about how far you've come in the course. We started with a simple tip calculator and ended with a fully functional app that you've built from the ground up.

Make sure to review the demo day tips as these will help you put together an engaging demo. Best of luck on demo day! 
/cc @codepathreview

**Pull request closed without merging**
